import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'ky': _kyStrings,
    'ru': _ruStrings,
    'en': _enStrings,
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
           _localizedValues['ky']?[key] ??
           key;
  }

  // Kyrgyz strings
  static const Map<String, String> _kyStrings = {
    // General
    'app_name': 'Jaidem',
    'loading': 'Жүктөлүүдө...',
    'error': 'Ката',
    'success': 'Ийгилик',
    'cancel': 'Жокко чыгаруу',
    'save': 'Сактоо',
    'delete': 'Өчүрүү',
    'edit': 'Өзгөртүү',
    'confirm': 'Ырастоо',
    'yes': 'Ооба',
    'no': 'Жок',
    'ok': 'Макул',
    'back': 'Артка',
    'next': 'Кийинки',
    'done': 'Даяр',
    'search': 'Издөө',
    'retry': 'Кайра аракет',
    'all': 'Баары',
    'clear': 'Тазалоо',
    'apply': 'Колдонуу',
    'reset': 'Баштапкы абалга келтирүү',
    'nothing_found': 'Эч нерсе табылган жок',
    'reload': 'Кайра жүктөө',
    'close': 'Жабуу',

    // Auth
    'login': 'Кирүү',
    'logout': 'Чыгуу',
    'email': 'Email',
    'password': 'Сырсөз',
    'forgot_password': 'Сырсөздү унуттуңузбу?',
    'login_error': 'Кирүү ишке ашкан жок',
    'welcome_message': 'Кош келиңиз',
    'login_to_account': 'Аккаунтка кирүү',
    'enter_credentials': 'Кирүү үчүн маалыматтарыңызды жазыңыз',
    'email_or_phone': 'Email же телефон',
    'enter_email_or_phone': 'Email же телефон жазыңыз',
    'enter_password': 'Сырсөз жазыңыз',
    'password_recovery': 'Сырсөздү калыбына келтирүү',
    'password_recovery_message': 'Сырсөздү калыбына келтирүү үчүн насаатчыңызга кайрылыңыз. Ал сизге сырсөздү кайра орнотууга жардам берет.',
    'understood': 'Түшүндүм',
    'sign_in': 'Кирүү',

    // Menu
    'menu': 'Меню',
    'profile': 'Профиль',
    'profile_info': 'Маалымат',
    'settings': 'Жөндөөлөр',
    'language': 'Тил',
    'change_language': 'Тилди өзгөртүү',
    'select_language': 'Тилди тандаңыз',
    'change_password': 'Сырсөздү өзгөртүү',
    'chats': 'Чаттар',
    'files': 'Файлдар',
    'about': 'Колдонмо жөнүндө',

    // Jaidems
    'jaidems': 'Жайдемчилер',
    'search_jaidems': 'Жайдемчилерди издөө...',
    'jaidems_not_found': 'Жайдемчилер табылган жок',
    'change_search_criteria': 'Издөө критерийлерин өзгөртүп көрүңүз',
    'advisors_not_found': 'Насаатчылар табылган жок',
    'advisors_not_found_description': 'Учурда насаатчылар жок',

    // Filters
    'filter': 'Чыпкалоо',
    'flow': 'Агым',
    'flow_number': 'Агым',
    'select_flow': 'Агым тандоо',
    'generation': 'Муун',
    'select_generation': 'Муун тандоо',
    'select_generation_first': 'Адегенде муунду тандаңыз',
    'state': 'Облус',
    'select_state': 'Облус тандоо',
    'select_state_first': 'Адегенде облусту тандаңыз',
    'region': 'Аймак',
    'select_region': 'Аймак тандоо',
    'select_district': 'Район тандоо',
    'select_district_first': 'Адегенде облусту тандаңыз',
    'select_village': 'Айыл/Шаар тандоо',
    'select_village_first': 'Адегенде районду тандаңыз',
    'no_districts_found': 'Район табылган жок',
    'no_villages_found': 'Айыл/Шаар табылган жок',
    'location': 'Туулган жери',
    'university': 'Университет',
    'select_university': 'Университет тандоо',
    'search_university': 'Университет издөө...',
    'universities_not_found': 'Университеттер табылган жок',
    'speciality': 'Адистик',
    'select_speciality': 'Адистик тандоо',
    'faculty': 'Факультет',
    'select_faculty': 'Факультет тандоо',
    'select_faculty_first': 'Адегенде факультет тандаңыз',
    'age': 'Жашы',
    'years_old': 'жаш',

    // Events
    'events': 'Иш-чаралар',
    'required_events': 'Милдеттүү иш-чаралар',
    'optional_events': 'Каалоочуларга',
    'event_details': 'Толук маалымат',
    'event_date': 'Датасы жана убактысы',
    'event_location': 'Жайгашкан жери',
    'event_generation': 'Муун',
    'event_description': 'Сүрөттөмө',
    'event_conditions': 'Шарттар',
    'event_contact': 'Байланыш',
    'event_video': 'Видео',
    'event_passed': 'Иш-чара өттү',
    'event_not_happened': 'Иш-чара али болгон жок',
    'reviews_after_event': 'Иш-чара өткөндөн кийин пикир калтыра аласыз',
    'required': 'Милдеттүү',
    'loading_events': 'Иш-чаралар жүктөлүүдө...',
    'events_load_error': 'Иш-чараларды жүктөөдө ката кетти',

    // Attendance
    'participants': 'Катышуучулар',
    'will_go': 'Барам',
    'will_not_go': 'Барбайм',
    'maybe': 'Ойлоном',
    'i_want_to_participate': 'Мен катышкым келет',
    'your_answer': 'Сиздин жообуңуз:',
    'change_answer': 'Жообуңузду өзгөртүү',
    'attendance_success': 'Сурам ийгиликтүү жөнөтүлдү!',
    'attendance_error': 'Жөнөтүү ишке ашкан жок, кийинчерээк кайра аракет кылыңыз.',
    'decline_reason': 'Барбай турган себебиңизди жазыңыз',
    'decline_reason_hint': 'Себебиңизди жазыңыз...',
    'send': 'Жөнөтүү',

    // Reviews
    'reviews': 'Пикирлер',
    'no_reviews': 'Пикирлер жок',
    'be_first_to_review': 'Биринчи болуп пикир калтырыңыз!',
    'write_review': 'Пикир жазуу',
    'edit_review': 'Пикирди түзөтүү',
    'new_review': 'Жаңы пикир',
    'your_review': 'Сиз',
    'write_your_review': 'Пикириңизди жазыңыз...',
    'delete_review': 'Пикирди өчүрүү',
    'delete_review_confirm': 'Сиз чындап эле пикириңизди өчүргүңүз келеби?',
    'review_save_error': 'Пикирди сактоо ишке ашкан жок',
    'review_delete_error': 'Пикирди өчүрүү ишке ашкан жок',

    // Likes
    'likes': 'Жактыруулар',

    // Goals
    'goals': 'Максаттар',
    'my_goals': 'Менин максаттарым',
    'manage_goals': 'Өзүңүздүн максаттарыңызды башкарыңыз',
    'add_goal': 'Максат кошуу',
    'add_task': 'Тапшырма кошуу',
    'add_indicator': 'Индикатор кошуу',
    'no_goals': 'Максаттар жок',
    'projects': 'Коммитеттер',
    'no_projects': 'Коммитеттер жок',
    'interested': 'кызыккан',
    'i_am_interested': 'Мен кызыгам',
    'not_interested': 'Кызыкпайм',
    'start_adding_goal': 'Биринчи максатыңызды кошуп баштаңыз!',
    'press_button_below': 'Төмөндөгү баскычты басыңыз',
    'progress': 'Прогресс',
    'deadline': 'Мөөнөт',
    'remaining': 'Калды',
    'days': 'күн',
    'no_deadline': 'Мөөнөт жок',
    'status_active': 'Активдүү',
    'status_in_progress': 'Аткарылууда',
    'status_completed': 'Аяктаган',
    'status_paused': 'Токтотулган',
    'status_changed': 'Өзгөртүлгөн',
    'status_cancelled': 'Жокко чыгарылган',
    'edit_goal': 'Максатты өзгөртүү',
    'new_goal': 'Жаңы максат',
    'update_goal_info': 'Максатыңыздын маалыматтарын жаңыртыңыз',
    'set_goal_for_success': 'Ийгиликке жетүү үчүн максат коюңуз',
    'basic_info': 'Негизги маалымат',
    'goal_name': 'Максаттын аты',
    'goal_name_hint': 'Англис тилин үйрөнүү',
    'description_optional': 'Сүрөттөмө (милдеттүү эмес)',
    'description_hint': 'Максатыңыз жөнүндө кыскача...',
    'deadline_and_frequency': 'Мөөнөт жана жыштык',
    'start_date': 'Баштоо күнү',
    'end_date': 'Аяктоо күнү',
    'currently': 'Учурда',
    'select_date': 'Күндү тандаңыз',
    'enter_manually': 'Кол менен киргизүү',
    'enter_date_hint': 'КК-АА-ЖЖЖЖ',
    'invalid_date_format': 'Туура эмес формат. КК-АА-ЖЖЖЖ форматында киргизиңиз',
    'frequency': 'Жыштыгы',
    'daily': 'Күн сайын',
    'weekly': 'Жума сайын',
    'monthly': 'Ай сайын',
    'indicators': 'Индикаторлор',
    'reminder': 'Эскертме',
    'reminder_time': 'Эскертме убактысы',
    'select_time': 'Убакытты тандаңыз',
    'goal_name_required': 'Максаттын аты талап кылынат.',
    'name_min_length': 'Аталыш кеминде 3 символдон турушу керек',
    'deadline_required': 'Максаттын мөөнөтү милдеттүү түрдө көрсөтүлүшү керек',
    'deadline_past_error': 'Максаттын аткарылуу күнү өткөн чакта болушу мүмкүн эмес.',
    'frequency_required': 'Жыштыгы милдеттүү',
    'reminder_time_required': 'Эскертме убактысы милдеттүү түрдө көрсөтүлүшү керек',
    'goal_updated_success': 'Максат ийгиликтүү жаңыртылды!',
    'goal_created_success': 'Максат ийгиликтүү түзүлдү!',
    'goal_and_indicators_created': 'Максат жана индикаторлор ийгиликтүү түзүлдү!',
    'indicator_create_error': 'Индикаторду түзүүдө ката кетти',
    'max_indicators': 'Максимум 3 индикатор кошууга болот',

    // Profile
    'edit_profile': 'Профилди түзөтүү',
    'about_me': 'Мен жөнүндө',
    'skills': 'Көндүмдөр',
    'in_what_i_can_help': 'Мен эмне менен жардам бере алам',
    'what_i_need': 'Мага эмне керек',
    'open_to': 'Мен ачыкмын',
    'vklad_to_jaidem': 'Jaidem\'ге салымым',
    'telegram': 'Telegram',
    'tags': 'Тегдер',
    'add_tag': 'Тег кошуу',
    'member_category': 'Мүчөлүк деңгээл',
    'interests': 'Кызыкчылыктар',
    'course_year': 'Курс',
    'village': 'Айыл/Шаар',
    'district': 'Район',
    'information': 'Маалымат',
    'unknown': 'Белгисиз',
    'call': 'Чалуу',
    'write_message': 'Жазуу',
    'contact': 'Байланыш',
    'booking_link': 'Брондоо шилтемеси',
    'phone': 'Телефон',

    // Forum
    'forum': 'Форум',
    'feed': 'Мүмкүнчүлүк',
    'posts': 'Посттор',
    'profile_tab': 'Профил',
    'comments': 'Комментарийлер',
    'write_comment': 'Комментарий жазыңыз...',
    'no_posts': 'Посттор жок',
    'no_posts_yet': 'Азырынча эч кандай пост жок',
    'user_has_no_posts': 'Бул колдонуучуда посттор жок',
    'error_loading_posts': 'Постторду жүктөөдө ката кетти',
    'share_profile': 'Профилди бөлүшүү',
    'search_hint': 'Издөө...',

    // Video
    'video_load_error': 'Видеону жүктөө ишке ашкан жок',
    'open_in_youtube': 'YouTube\'да ачуу',

    // Languages
    'kyrgyz': 'Кыргызча',
    'russian': 'Орусча',
    'english': 'Англисче',

    // Errors
    'error_occurred': 'Ката кетти',
    'try_again': 'Кайра аракет кылыңыз',
    'no_internet': 'Интернет байланышы жок',

    // Menu / Drawer
    'main_section': 'Негизги',
    'knowledge_base': 'Билим базасы',
    'trainings': 'Тренингди баалоо',
    'chat_list': 'Чаттардын тизмеси',
    'chat_with_admin': 'Администратор менен баарлашуу',
    'chat_with_mentor': 'Насаатчы менен баарлашуу',
    'settings_section': 'Орнотуулар',
    'notifications': 'Эскертмелер',
    'welcome': 'Кош келиңиз!',
    'select_menu_item': 'Менюдан керектүү бөлүмдү тандаңыз',
    'signing_out': 'Чыгууда...',
    'sign_out': 'Аккаунттан чыгуу',
    'sign_out_confirm': 'Чыгууну каалайсызбы?',
    'sign_out_description': 'Аккаунтуңуздан чыккандан кийин кайра кирүү керек болот',
    'yes_sign_out': 'Ооба, чыгуу',
    'sign_out_failed': 'Чыгуу ишке ашпады',

    // Bottom Navigation
    'nav_home': 'Башкы',
    'nav_jaidem': 'Жайдем',
    'nav_news': 'Жаңылыктар',
    'nav_events': 'Иш-чара',
    'nav_profile': 'Профиль',

    // Account Deletion
    'delete_account': 'Аккаунтту өчүрүү',
    'delete_account_title': 'Аккаунтту өчүрүү',
    'delete_account_description': 'Аккаунтуңузду өчүргөнүңүздө, бардык маалыматтарыңыз биротоло жок болот. Бул аракетти кайра кайтаруу мүмкүн эмес.',
    'delete_account_confirm': 'Чынында эле аккаунтуңузду өчүргүңүз келеби?',
    'yes_delete': 'Ооба, өчүрүү',
    'account_deleted': 'Аккаунт ийгиликтүү өчүрүлдү',
    'delete_account_error': 'Аккаунтту өчүрүү ишке ашкан жок',

    // Content Moderation
    'report': 'Кабарлоо',
    'report_content': 'Контентти кабарлоо',
    'report_reason': 'Кабарлоо себеби',
    'report_spam': 'Спам',
    'report_inappropriate': 'Туура эмес контент',
    'report_harassment': 'Кордоо же тынчсыздандыруу',
    'report_other': 'Башка',
    'report_sent': 'Кабарлооңуз жөнөтүлдү',
    'report_description': 'Кошумча маалымат (милдеттүү эмес)',
    'report_comment': 'Комментарийди кабарлоо',
    'content_filtered_warning': 'Билдирүүңүздө туура эмес сөздөр бар. Текстти өзгөртүңүз.',
    'report_user': 'Колдонуучуну кабарлоо',
    'block_user': 'Колдонуучуну бөгөттөө',
    'block_user_confirm': 'Бул колдонуучуну бөгөттөөнү каалайсызбы?',
    'user_blocked': 'Колдонуучу бөгөттөлдү',
    'unblock_user': 'Бөгөттөн чыгаруу',
    'user_unblocked': 'Колдонуучу бөгөттөн чыгарылды',

    // Terms and Conditions
    'terms_title': 'Колдонуу шарттары',
    'terms_accept': 'Мен колдонуу шарттарын кабыл алам',
    'terms_accept_button': 'Кабыл алам',
    'terms_must_accept': 'Улантуу үчүн шарттарды кабыл алыңыз',
    'privacy_policy': 'Купуялык саясаты',
    'terms_content': 'JAIDEM колдонмосун колдонуу менен сиз төмөнкү Колдонуучу лицензия келишимин (EULA) кабыл аласыз:\\n\\nМААНИЛҮҮ: JAIDEM туура эмес контентке жана орой же коомдук нормаларга каршы келген билдирүүлөргө каршы экендигин билдирет.\\n\\n1. Урматтоо: Башка колдонуучуларга урмат менен мамиле кылыңыз. Кордоо, коркутуу жана кемсинтүү катуу тыюу салынат.\\n2. Туура эмес контент: Зыяндуу, кордоочу, порнографиялык же мыйзамсыз контентти жайгаштыруу тыюу салынат. Колдонмо автоматтык түрдө контентти текшерет.\\n3. Кабарлоо жана бөгөттөө: Колдонуучулар туура эмес контентти же кыянатчыл колдонуучуларды кабарлоо баскычы аркылуу билдире алышат. Ошондой эле каалаган колдонуучуну бөгөттөп, аларды лентаңыздан алып салууга болот.\\n4. Жеке маалымат: Башкалардын жеке маалыматын уруксатсыз бөлүшпөңүз.\\n5. Спам: Спам же жарнама жайгаштырбаңыз.\\n\\nЖАЗАЛОО ЧАРАЛАРЫ: Бул эрежелерди бузган колдонуучулар дароо бөгөттөлөт жана алардын контенти 24 сааттын ичинде өчүрүлөт. Кабарлоолор иштеп чыгуучу тарабынан каралат жана тиешелүү чаралар 24 саат ичинде көрүлөт.\\n\\nКолдонмону улантуу менен сиз бул шарттарды толук кабыл аласыз.',

    // Training
    'training_rating': 'Баалоо',
    'training_questions': 'Суроолор',
    'training_flow_info': 'Поток маалыматы',
    'training_name': 'Аты',
    'training_description': 'Сүрөттөмө',
    'training_year': 'Жыл',
    'training_attendance_stats': 'Катышуу статистикасы',
    'training_attendance': 'Катышуу',
    'training_present': 'Катышты',
    'training_absent': 'Келбеди',
    'training_respectful': 'Себептүү',
    'training_total_participants': 'Жалпы катышуучулар',
    'training_participants_list': 'Катышуучулар тизмеси',
    'training_already_answered': 'Сиз мурун жооп бергенсиз',
    'training_rating_accepted': 'Тренинг боюнча баалооңуз кабыл алынды',
    'training_rate_training': 'Тренингди баалаңыз',
    'training_opinion_important': 'Сиздин пикириңиз биз үчүн маанилүү',
    'training_answer_questions': 'Суроолорго жооп берүү',
    'training_answer_all_questions': 'Бардык суроолорго жооп бериңиз',
    'training_answers_sent': 'Жооптор ийгиликтүү жөнөтүлдү',
    'training_write_comment': 'Пикириңизди жазыңыз...',
    'training_submit': 'Жөнөтүү',

    // Opros (Survey)
    'opros_before_survey': 'Алдын ала сурамжылоо',
    'opros_after_survey': 'Кийинки сурамжылоо',
    'opros_fill_survey': 'Сурамжылоону толтуруу',
    'opros_opens_on': 'Ачылуу күнү: ',
    'opros_submit': 'Жөнөтүү',
    'opros_answer_required': 'Суроого жооп бериңиз',
    'opros_submitted_success': 'Сурамжылоо ийгиликтүү жөнөтүлдү!',
    'opros_write_answer': 'Жообуңузду жазыңыз...',
    'opros_survey': 'Сурамжылоо',

    // Birthday reactions
    'birthday_congrats_button': 'Куттуктоо 🎉',
    'birthday_people_reacted': 'Сизди куттуктагандар',
    'birthday_already_reacted': 'Куттуктадыңыз ✓',
    'birthday_today': 'Бүгүн туулган күнү!',
    'date_of_birth': 'Туулган күнү',
    'birthday_send_reaction': 'Куттуктоо жөнөтүлдү!',

    // Posts
    'delete_post_title': 'Постту өчүрүү',
    'delete_post_confirm': 'Бул постту өчүргүңүз келеби?',
    'post_deleted': 'Пост ийгиликтүү өчүрүлдү',
    'post_updated': 'Пост жаңыртылды',
    'post_created': 'Пост түзүлдү',
    'no_posts_hint': 'Биринчи постуңузду жазыңыз',
    'write_thoughts': 'Ойлоруңузду жазыңыз...',
    'new_post': 'Жаңы пост',
    'edit_post': 'Постту түзөтүү',
    'update_post_hint': 'Постуңузду жаңыртыңыз',
    'share_thoughts': 'Ойлоруңуз менен бөлүшүңүз',
    'photo': 'Сүрөт',
    'add_photo': 'Сүрөт кошуу',
    'select_from_gallery': 'Галереядан тандоо',
    'uploading': 'Жүктөлүүдө...',
    'content_label': 'Мазмуну',
    'content_required': 'Мазмунду жазыңыз',
    'saving': 'Сакталууда...',
    'publish': 'Жарыялоо',
    'image_upload_error': 'Сүрөт жүктөөдө ката',

    // Change Password
    'set_new_password': 'Жаңы сырсөз орнотуңуз',
    'password_requirements': 'Сырсөз 8 белгиден кем болбошу керек жана тамгалар менен сандарды камтышы керек.',
    'current_password': 'Учурдагы сырсөз',
    'enter_current_password': 'Учурдагы сырсөзүңүздү киргизиңиз',
    'new_password': 'Жаңы сырсөз',
    'enter_new_password': 'Жаңы сырсөз киргизиңиз',
    'password_min_length': 'Сырсөз 8 белгиден кем болбошу керек',
    'confirm_password': 'Сырсөздү ырастаңыз',
    'repeat_new_password': 'Жаңы сырсөздү кайталаңыз',
    'passwords_dont_match': 'Сырсөздөр дал келбейт',
    'password_changed': 'Сырсөз ийгиликтүү өзгөртүлдү!',

    // Forum
    'see_more': 'Көбүрөөк көрүү',
    'just_now': 'азыр',
    'minutes_short': 'мүн',
    'hours_short': 'с',
    'days_short': 'к',
    'weeks_short': 'апт',
    'months_short': 'ай',
    'liked': 'Жактырдым',
    'reply_action': 'Жооп',
    'reply_to': 'жооп берүү',
    'no_comments': 'Комментарий жок',
    'be_first_comment': 'Биринчи болуп комментарий калтырыңыз!',
    'write_reply': 'Жооп жазуу...',
    'post_single': 'Пост',
    'post_not_found': 'Пост табылган жок',
    'anonymous': 'Аноним',

    // Training page
    'trainings_title': 'Тренинги',
    'training_subtitle': 'Окуу тренингдери',
    'no_trainings': 'Тренингдер жок',
    'no_trainings_available': 'Учурда жеткиликтүү тренингдер жок',
    'no_questions': 'Суроолор жок',

    // Profile Edit
    'education': 'Билим',
    'interests_and_skills': 'Кызыкчылыктар жана көндүмдөр',
    'contact_info': 'Байланыш маалыматы',
    'course_year_hint': 'Окуу жылы',
    'interests_hint': 'Кызыкчылыктар (мис: Футбол, Китеп окуу...)',
    'skills_hint': 'Көндүмдөр (мис: Программирование, Дизайн...)',
    'phone_hint': 'Телефон номери',
    'whatsapp_hint': 'WhatsApp номери',
    'instagram_hint': 'Instagram колдонуучу аты',
    'profile_saved': 'Профиль ийгиликтүү сакталды',
    'save_error': 'Сактоодо ката',
    'image_uploaded': 'Сүрөт ийгиликтүү жүктөлдү',
    'tap_to_change_photo': 'Сүрөттү өзгөртүү үчүн басыңыз',
    'select_birthday': 'Туулган күнүңүздү тандаңыз',
    'select_university_hint': 'Университет тандаңыз',
    'select_speciality_hint': 'Адистик тандаңыз',
    'specialities_not_found': 'Адистиктер табылган жок',
    'no_data': 'Маалымат жок',
    'full_profile': 'Толук профилди көрүү',
    'no_university': 'Университетте окубайм',
    'other_education': 'Башка билим',
    'work_experience': 'Иш тажрыйбасы',
    'add_school': 'Окуу жай кошуу',
    'add_work_place': 'Иш жай кошуу',
    'success_history': 'Ийгиликтер тарыхы',
    'add_success': 'Ийгилик кошуу',
    'success_name': 'Ийгиликтин аты',
    'additional_education': 'Кошумча билим',
    'add_additional_education': 'Кошумча билим кошуу',
    'additional_education_title': 'Аталышы',
    'school_name': 'Окуу жайдын аты',
    'work_place_name': 'Иш жайдын аты',
    'position': 'Кызматы',
    'delete_confirm': 'Чын эле өчүргүңүз келеби?',
    'description': 'Сүрөттөмө',

    // Jaidem popup
    'age_label': 'жаш',
    'education_place': 'окуу жайы',
    'region_label': 'облус',
    'additional_info': 'Кошумча маалымат',
    'flow_label': 'Агым',
    'interests_label': 'Кызыкчылыктар',
    'skills_label': 'Көндүмдөр',
    'phone_label': 'Телефон',
    'about_me_hint': 'Өзүңүз тууралуу маалымат жазыңыз...',
    'specialty': 'Адистик',
    'no_universities_found': 'Университеттер табылган жок',
    'year_suffix': '-жыл',

    // Person details
    'label_age': 'Жашы:',
    'label_course_year': 'Окуу жылы:',
    'label_specialty': 'Адистик:',
    'label_region': 'Аймак:',
    'label_village_city': 'Айыл/шаар:',
    'label_interests_skills': 'Кызыкчылыктары/көндүмдөрү:',
    'label_phone': 'Телефон:',
    'label_email': 'Email:',
    'specialty_profession': 'Адис/кесип: ',
    'university_label': 'Университет: ',

    // Stories
    'stories_your_story': 'Сенин сторисиң',
    'stories_add': 'Сторис кошуу',
    'stories_delete': 'Өчүрүү',
    'stories_delete_confirm': 'Бул стористи өчүрөсүзбү?',
    'stories_deleted': 'Сторис өчүрүлдү',
    'stories_upload_failed': 'Сүрөт жүктөлгөн жок',
    'stories_create_failed': 'Сторис түзүлгөн жок',
    'stories_reply_hint': 'Билдирүү жазыңыз...',
    'stories_reply_sent': 'Жөнөтүлдү',
    'stories_reply_failed': 'Жөнөтүлгөн жок',
  };

  // Russian strings
  static const Map<String, String> _ruStrings = {
    // General
    'app_name': 'Jaidem',
    'loading': 'Загрузка...',
    'error': 'Ошибка',
    'success': 'Успех',
    'cancel': 'Отмена',
    'save': 'Сохранить',
    'delete': 'Удалить',
    'edit': 'Изменить',
    'confirm': 'Подтвердить',
    'yes': 'Да',
    'no': 'Нет',
    'ok': 'ОК',
    'back': 'Назад',
    'next': 'Далее',
    'done': 'Готово',
    'search': 'Поиск',
    'retry': 'Повторить',
    'all': 'Все',
    'clear': 'Очистить',
    'apply': 'Применить',
    'reset': 'Сбросить',
    'nothing_found': 'Ничего не найдено',
    'reload': 'Перезагрузить',
    'close': 'Закрыть',

    // Auth
    'login': 'Вход',
    'logout': 'Выход',
    'email': 'Email',
    'password': 'Пароль',
    'forgot_password': 'Забыли пароль?',
    'login_error': 'Ошибка входа',
    'welcome_message': 'Добро пожаловать',
    'login_to_account': 'Войти в аккаунт',
    'enter_credentials': 'Введите данные для входа',
    'email_or_phone': 'Email или телефон',
    'enter_email_or_phone': 'Введите email или телефон',
    'enter_password': 'Введите пароль',
    'password_recovery': 'Восстановление пароля',
    'password_recovery_message': 'Для восстановления пароля обратитесь к вашему ментору. Он поможет вам сбросить пароль и восстановить доступ к аккаунту.',
    'understood': 'Понятно',
    'sign_in': 'Войти',

    // Menu
    'menu': 'Меню',
    'profile': 'Профиль',
    'profile_info': 'Информация',
    'settings': 'Настройки',
    'language': 'Язык',
    'change_language': 'Изменить язык',
    'select_language': 'Выберите язык',
    'change_password': 'Изменить пароль',
    'chats': 'Чаты',
    'files': 'Файлы',
    'about': 'О приложении',

    // Jaidems
    'jaidems': 'Джайдемовцы',
    'search_jaidems': 'Поиск джайдемовцев...',
    'jaidems_not_found': 'Джайдемовцы не найдены',
    'change_search_criteria': 'Попробуйте изменить критерии поиска',
    'advisors_not_found': 'Наставники не найдены',
    'advisors_not_found_description': 'На данный момент наставники отсутствуют',

    // Filters
    'filter': 'Фильтр',
    'flow': 'Поток',
    'flow_number': 'Поток',
    'select_flow': 'Выберите поток',
    'generation': 'Поколение',
    'select_generation': 'Выберите поколение',
    'select_generation_first': 'Сначала выберите поколение',
    'state': 'Область',
    'select_state': 'Выберите область',
    'select_state_first': 'Сначала выберите область',
    'region': 'Регион',
    'select_region': 'Выберите регион',
    'select_district': 'Выберите район',
    'select_district_first': 'Сначала выберите область',
    'select_village': 'Выберите город/село',
    'select_village_first': 'Сначала выберите район',
    'no_districts_found': 'Районы не найдены',
    'no_villages_found': 'Города/села не найдены',
    'location': 'Место рождения',
    'university': 'Университет',
    'select_university': 'Выберите университет',
    'search_university': 'Поиск университета...',
    'universities_not_found': 'Университеты не найдены',
    'speciality': 'Специальность',
    'select_speciality': 'Выберите специальность',
    'faculty': 'Факультет',
    'select_faculty': 'Выберите факультет',
    'select_faculty_first': 'Сначала выберите факультет',
    'age': 'Возраст',
    'years_old': 'лет',

    // Events
    'events': 'Мероприятия',
    'required_events': 'Обязательные мероприятия',
    'optional_events': 'Для желающих',
    'event_details': 'Подробнее',
    'event_date': 'Дата и время',
    'event_location': 'Местоположение',
    'event_generation': 'Поколение',
    'event_description': 'Описание',
    'event_conditions': 'Условия',
    'event_contact': 'Контакты',
    'event_video': 'Видео',
    'event_passed': 'Мероприятие прошло',
    'event_not_happened': 'Мероприятие еще не состоялось',
    'reviews_after_event': 'Вы сможете оставить отзыв после мероприятия',
    'required': 'Обязательно',
    'loading_events': 'Загрузка мероприятий...',
    'events_load_error': 'Ошибка загрузки мероприятий',

    // Attendance
    'participants': 'Участники',
    'will_go': 'Пойду',
    'will_not_go': 'Не пойду',
    'maybe': 'Думаю',
    'i_want_to_participate': 'Хочу участвовать',
    'your_answer': 'Ваш ответ:',
    'change_answer': 'Изменить ответ',
    'attendance_success': 'Заявка успешно отправлена!',
    'attendance_error': 'Не удалось отправить, попробуйте позже.',
    'decline_reason': 'Укажите причину отказа',
    'decline_reason_hint': 'Напишите причину...',
    'send': 'Отправить',

    // Reviews
    'reviews': 'Отзывы',
    'no_reviews': 'Отзывов нет',
    'be_first_to_review': 'Будьте первым, кто оставит отзыв!',
    'write_review': 'Написать отзыв',
    'edit_review': 'Редактировать отзыв',
    'new_review': 'Новый отзыв',
    'your_review': 'Вы',
    'write_your_review': 'Напишите ваш отзыв...',
    'delete_review': 'Удалить отзыв',
    'delete_review_confirm': 'Вы действительно хотите удалить свой отзыв?',
    'review_save_error': 'Не удалось сохранить отзыв',
    'review_delete_error': 'Не удалось удалить отзыв',

    // Likes
    'likes': 'Лайки',

    // Goals
    'goals': 'Цели',
    'my_goals': 'Мои цели',
    'manage_goals': 'Управляйте своими целями',
    'add_goal': 'Добавить цель',
    'add_task': 'Добавить задачу',
    'add_indicator': 'Добавить индикатор',
    'no_goals': 'Нет целей',
    'projects': 'Комитеты',
    'no_projects': 'Нет комитетов',
    'interested': 'интересуются',
    'i_am_interested': 'Мне интересно',
    'not_interested': 'Не интересно',
    'start_adding_goal': 'Начните добавлять свою первую цель!',
    'press_button_below': 'Нажмите кнопку внизу',
    'progress': 'Прогресс',
    'deadline': 'Срок',
    'remaining': 'Осталось',
    'days': 'дн.',
    'no_deadline': 'Без срока',
    'status_active': 'Активная',
    'status_in_progress': 'В процессе',
    'status_completed': 'Завершена',
    'status_paused': 'Приостановлена',
    'status_changed': 'Изменено',
    'status_cancelled': 'Отменено',
    'edit_goal': 'Редактировать цель',
    'new_goal': 'Новая цель',
    'update_goal_info': 'Обновите информацию о вашей цели',
    'set_goal_for_success': 'Поставьте цель для достижения успеха',
    'basic_info': 'Основная информация',
    'goal_name': 'Название цели',
    'goal_name_hint': 'Выучить английский язык',
    'description_optional': 'Описание (необязательно)',
    'description_hint': 'Кратко о вашей цели...',
    'deadline_and_frequency': 'Срок и периодичность',
    'start_date': 'Дата начала',
    'end_date': 'Дата окончания',
    'currently': 'В настоящее время',
    'select_date': 'Выберите дату',
    'enter_manually': 'Ввести вручную',
    'enter_date_hint': 'ДД-ММ-ГГГГ',
    'invalid_date_format': 'Неверный формат. Введите в формате ДД-ММ-ГГГГ',
    'frequency': 'Периодичность',
    'daily': 'Ежедневно',
    'weekly': 'Еженедельно',
    'monthly': 'Ежемесячно',
    'indicators': 'Индикаторы',
    'reminder': 'Напоминание',
    'reminder_time': 'Время напоминания',
    'select_time': 'Выберите время',
    'goal_name_required': 'Название цели обязательно.',
    'name_min_length': 'Название должно содержать минимум 3 символа',
    'deadline_required': 'Дата цели обязательна',
    'deadline_past_error': 'Дата цели не может быть в прошлом.',
    'frequency_required': 'Периодичность обязательна',
    'reminder_time_required': 'Время напоминания обязательно',
    'goal_updated_success': 'Цель успешно обновлена!',
    'goal_created_success': 'Цель успешно создана!',
    'goal_and_indicators_created': 'Цель и индикаторы успешно созданы!',
    'indicator_create_error': 'Ошибка при создании индикатора',
    'max_indicators': 'Максимум можно добавить 3 индикатора',

    // Profile
    'edit_profile': 'Редактировать профиль',
    'about_me': 'Обо мне',
    'skills': 'Навыки',
    'in_what_i_can_help': 'Чем я могу помочь',
    'what_i_need': 'Что мне нужно',
    'open_to': 'Я открыт(а) к',
    'vklad_to_jaidem': 'Мой вклад в Jaidem',
    'telegram': 'Telegram',
    'tags': 'Теги',
    'member_category': 'Членская категория',
    'add_tag': 'Добавить тег',
    'interests': 'Интересы',
    'course_year': 'Курс',
    'village': 'Город/село',
    'district': 'Район',
    'information': 'Информация',
    'unknown': 'Неизвестно',
    'call': 'Позвонить',
    'write_message': 'Написать',
    'contact': 'Контакты',
    'booking_link': 'Ссылка для бронирования',
    'phone': 'Телефон',

    // Forum
    'forum': 'Форум',
    'feed': 'Мүмкүнчүлүк',
    'posts': 'Посты',
    'profile_tab': 'Профиль',
    'comments': 'Комментарии',
    'write_comment': 'Напишите комментарий...',
    'no_posts': 'Нет постов',
    'no_posts_yet': 'Пока нет ни одного поста',
    'user_has_no_posts': 'У этого пользователя нет постов',
    'error_loading_posts': 'Ошибка загрузки постов',
    'share_profile': 'Поделиться профилем',
    'search_hint': 'Поиск...',

    // Video
    'video_load_error': 'Не удалось загрузить видео',
    'open_in_youtube': 'Открыть в YouTube',

    // Languages
    'kyrgyz': 'Кыргызский',
    'russian': 'Русский',
    'english': 'Английский',

    // Errors
    'error_occurred': 'Произошла ошибка',
    'try_again': 'Попробуйте снова',
    'no_internet': 'Нет подключения к интернету',

    // Menu / Drawer
    'main_section': 'Основное',
    'knowledge_base': 'База знаний',
    'trainings': 'Оценить тренинг',
    'chat_list': 'Список чатов',
    'chat_with_admin': 'Чат с администратором',
    'chat_with_mentor': 'Чат с наставником',
    'settings_section': 'Настройки',
    'notifications': 'Уведомления',
    'welcome': 'Добро пожаловать!',
    'select_menu_item': 'Выберите нужный раздел в меню',
    'signing_out': 'Выход...',
    'sign_out': 'Выйти из аккаунта',
    'sign_out_confirm': 'Вы хотите выйти?',
    'sign_out_description': 'После выхода из аккаунта потребуется повторный вход',
    'yes_sign_out': 'Да, выйти',
    'sign_out_failed': 'Не удалось выйти',

    // Bottom Navigation
    'nav_home': 'Главная',
    'nav_jaidem': 'Жайдем',
    'nav_news': 'Новости',
    'nav_events': 'События',
    'nav_profile': 'Профиль',

    // Account Deletion
    'delete_account': 'Удалить аккаунт',
    'delete_account_title': 'Удаление аккаунта',
    'delete_account_description': 'При удалении аккаунта все ваши данные будут безвозвратно удалены. Это действие нельзя отменить.',
    'delete_account_confirm': 'Вы действительно хотите удалить свой аккаунт?',
    'yes_delete': 'Да, удалить',
    'account_deleted': 'Аккаунт успешно удален',
    'delete_account_error': 'Не удалось удалить аккаунт',

    // Content Moderation
    'report': 'Пожаловаться',
    'report_content': 'Пожаловаться на контент',
    'report_reason': 'Причина жалобы',
    'report_spam': 'Спам',
    'report_inappropriate': 'Неприемлемый контент',
    'report_harassment': 'Оскорбление или травля',
    'report_other': 'Другое',
    'report_sent': 'Ваша жалоба отправлена',
    'report_description': 'Дополнительная информация (необязательно)',
    'report_comment': 'Пожаловаться на комментарий',
    'content_filtered_warning': 'Ваше сообщение содержит недопустимые слова. Измените текст.',
    'report_user': 'Пожаловаться на пользователя',
    'block_user': 'Заблокировать пользователя',
    'block_user_confirm': 'Вы хотите заблокировать этого пользователя?',
    'user_blocked': 'Пользователь заблокирован',
    'unblock_user': 'Разблокировать',
    'user_unblocked': 'Пользователь разблокирован',

    // Terms and Conditions
    'terms_title': 'Условия использования',
    'terms_accept': 'Я принимаю условия использования',
    'terms_accept_button': 'Принимаю',
    'terms_must_accept': 'Для продолжения примите условия',
    'privacy_policy': 'Политика конфиденциальности',
    'terms_content': 'Используя приложение Jaidem, вы принимаете следующее Лицензионное соглашение (EULA):\\n\\nВАЖНО: Jaidem придерживается политики АБСОЛЮТНОЙ НЕТЕРПИМОСТИ к неприемлемому контенту и оскорбительному поведению пользователей.\\n\\n1. Уважение: Относитесь к другим пользователям с уважением. Оскорбления, травля и дискриминация строго запрещены.\\n2. Неприемлемый контент: Публикация вредоносного, оскорбительного, порнографического или незаконного контента запрещена. Приложение автоматически фильтрует контент.\\n3. Жалобы и блокировка: Пользователи могут сообщить о неприемлемом контенте или оскорбительных пользователях с помощью кнопки «Пожаловаться». Вы также можете заблокировать любого пользователя, чтобы немедленно убрать его из вашей ленты.\\n4. Личные данные: Не распространяйте чужие личные данные без разрешения.\\n5. Спам: Не публикуйте спам или рекламу.\\n\\nМЕРЫ: Пользователи, нарушающие эти правила, будут немедленно заблокированы, а их контент удалён в течение 24 часов. Все жалобы рассматриваются разработчиком, и соответствующие меры принимаются в течение 24 часов.\\n\\nПродолжая использование приложения, вы полностью принимаете эти условия.',

    // Training
    'training_rating': 'Оценка',
    'training_questions': 'Вопросы',
    'training_flow_info': 'Информация о потоке',
    'training_name': 'Название',
    'training_description': 'Описание',
    'training_year': 'Год',
    'training_attendance_stats': 'Статистика посещаемости',
    'training_attendance': 'Посещаемость',
    'training_present': 'Присутствовал',
    'training_absent': 'Отсутствовал',
    'training_respectful': 'Уважительная причина',
    'training_total_participants': 'Всего участников',
    'training_participants_list': 'Список участников',
    'training_already_answered': 'Вы уже ответили',
    'training_rating_accepted': 'Ваша оценка тренинга принята',
    'training_rate_training': 'Оцените тренинг',
    'training_opinion_important': 'Ваше мнение важно для нас',
    'training_answer_questions': 'Ответить на вопросы',
    'training_answer_all_questions': 'Ответьте на все вопросы',
    'training_answers_sent': 'Ответы успешно отправлены',
    'training_write_comment': 'Напишите ваш комментарий...',
    'training_submit': 'Отправить',

    // Opros (Survey)
    'opros_before_survey': 'Опрос ДО',
    'opros_after_survey': 'Опрос ПОСЛЕ',
    'opros_fill_survey': 'Пройти опрос',
    'opros_opens_on': 'Откроется: ',
    'opros_submit': 'Отправить',
    'opros_answer_required': 'Ответьте на вопрос',
    'opros_submitted_success': 'Опрос успешно отправлен!',
    'opros_write_answer': 'Напишите ваш ответ...',
    'opros_survey': 'Опрос',

    // Birthday reactions
    'birthday_congrats_button': 'Поздравить 🎉',
    'birthday_people_reacted': 'Вас поздравили',
    'birthday_already_reacted': 'Вы поздравили ✓',
    'birthday_today': 'Сегодня день рождения!',
    'date_of_birth': 'Дата рождения',
    'birthday_send_reaction': 'Поздравление отправлено!',

    // Posts
    'delete_post_title': 'Удалить пост',
    'delete_post_confirm': 'Вы хотите удалить этот пост?',
    'post_deleted': 'Пост успешно удален',
    'post_updated': 'Пост обновлен',
    'post_created': 'Пост создан',
    'no_posts_hint': 'Напишите свой первый пост',
    'write_thoughts': 'Напишите ваши мысли...',
    'new_post': 'Новый пост',
    'edit_post': 'Редактировать пост',
    'update_post_hint': 'Обновите ваш пост',
    'share_thoughts': 'Поделитесь мыслями',
    'photo': 'Фото',
    'add_photo': 'Добавить фото',
    'select_from_gallery': 'Выбрать из галереи',
    'uploading': 'Загрузка...',
    'content_label': 'Содержание',
    'content_required': 'Напишите содержимое',
    'saving': 'Сохранение...',
    'publish': 'Опубликовать',
    'image_upload_error': 'Ошибка загрузки изображения',

    // Change Password
    'set_new_password': 'Установите новый пароль',
    'password_requirements': 'Пароль должен содержать не менее 8 символов и включать буквы и цифры.',
    'current_password': 'Текущий пароль',
    'enter_current_password': 'Введите текущий пароль',
    'new_password': 'Новый пароль',
    'enter_new_password': 'Введите новый пароль',
    'password_min_length': 'Пароль должен содержать не менее 8 символов',
    'confirm_password': 'Подтвердите пароль',
    'repeat_new_password': 'Повторите новый пароль',
    'passwords_dont_match': 'Пароли не совпадают',
    'password_changed': 'Пароль успешно изменен!',

    // Forum
    'see_more': 'Показать еще',
    'just_now': 'сейчас',
    'minutes_short': 'мин',
    'hours_short': 'ч',
    'days_short': 'д',
    'weeks_short': 'нед',
    'months_short': 'мес',
    'liked': 'Нравится',
    'reply_action': 'Ответ',
    'reply_to': 'ответить',
    'no_comments': 'Нет комментариев',
    'be_first_comment': 'Будьте первым, кто оставит комментарий!',
    'write_reply': 'Написать ответ...',
    'post_single': 'Пост',
    'post_not_found': 'Пост не найден',
    'anonymous': 'Аноним',

    // Training page
    'trainings_title': 'Тренинги',
    'training_subtitle': 'Учебные тренинги',
    'no_trainings': 'Нет тренингов',
    'no_trainings_available': 'Нет доступных тренингов',
    'no_questions': 'Нет вопросов',

    // Profile Edit
    'education': 'Образование',
    'interests_and_skills': 'Интересы и навыки',
    'contact_info': 'Контактная информация',
    'course_year_hint': 'Год обучения',
    'interests_hint': 'Интересы (напр: Футбол, Чтение...)',
    'skills_hint': 'Навыки (напр: Программирование, Дизайн...)',
    'phone_hint': 'Номер телефона',
    'whatsapp_hint': 'Номер WhatsApp',
    'instagram_hint': 'Имя пользователя Instagram',
    'profile_saved': 'Профиль успешно сохранен',
    'save_error': 'Ошибка сохранения',
    'image_uploaded': 'Изображение загружено',
    'tap_to_change_photo': 'Нажмите, чтобы изменить фото',
    'select_birthday': 'Выберите дату рождения',
    'select_university_hint': 'Выберите университет',
    'select_speciality_hint': 'Выберите специальность',
    'specialities_not_found': 'Специальности не найдены',
    'no_data': 'Нет данных',
    'full_profile': 'Смотреть полный профиль',
    'no_university': 'Не учусь в университете',
    'other_education': 'Другое образование',
    'work_experience': 'Опыт работы',
    'add_school': 'Добавить учебное заведение',
    'add_work_place': 'Добавить место работы',
    'success_history': 'История успехов',
    'add_success': 'Добавить успех',
    'success_name': 'Название успеха',
    'additional_education': 'Дополнительное образование',
    'add_additional_education': 'Добавить образование',
    'additional_education_title': 'Название',
    'school_name': 'Название учебного заведения',
    'work_place_name': 'Название места работы',
    'position': 'Должность',
    'delete_confirm': 'Вы уверены, что хотите удалить?',
    'description': 'Описание',

    // Jaidem popup
    'age_label': 'лет',
    'education_place': 'учеб. зав.',
    'region_label': 'область',
    'additional_info': 'Дополнительная информация',
    'flow_label': 'Поток',
    'interests_label': 'Интересы',
    'skills_label': 'Навыки',
    'phone_label': 'Телефон',
    'about_me_hint': 'Напишите о себе...',
    'specialty': 'Специальность',
    'no_universities_found': 'Университеты не найдены',
    'year_suffix': '-й год',

    // Person details
    'label_age': 'Возраст:',
    'label_course_year': 'Курс:',
    'label_specialty': 'Специальность:',
    'label_region': 'Регион:',
    'label_village_city': 'Город/село:',
    'label_interests_skills': 'Интересы/навыки:',
    'label_phone': 'Телефон:',
    'label_email': 'Email:',
    'specialty_profession': 'Специальность: ',
    'university_label': 'Университет: ',

    // Stories
    'stories_your_story': 'Твоя история',
    'stories_add': 'Добавить историю',
    'stories_delete': 'Удалить',
    'stories_delete_confirm': 'Удалить эту историю?',
    'stories_deleted': 'История удалена',
    'stories_upload_failed': 'Не удалось загрузить фото',
    'stories_create_failed': 'Не удалось создать историю',
    'stories_reply_hint': 'Написать сообщение...',
    'stories_reply_sent': 'Отправлено',
    'stories_reply_failed': 'Не удалось отправить',
  };

  // English strings
  static const Map<String, String> _enStrings = {
    // General
    'app_name': 'Jaidem',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'confirm': 'Confirm',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'OK',
    'back': 'Back',
    'next': 'Next',
    'done': 'Done',
    'search': 'Search',
    'retry': 'Retry',
    'all': 'All',
    'clear': 'Clear',
    'apply': 'Apply',
    'reset': 'Reset',
    'nothing_found': 'Nothing found',
    'reload': 'Reload',
    'close': 'Close',

    // Auth
    'login': 'Login',
    'logout': 'Logout',
    'email': 'Email',
    'password': 'Password',
    'forgot_password': 'Forgot password?',
    'login_error': 'Login failed',
    'welcome_message': 'Welcome',
    'login_to_account': 'Sign in to your account',
    'enter_credentials': 'Enter your credentials to sign in',
    'email_or_phone': 'Email or phone',
    'enter_email_or_phone': 'Enter email or phone',
    'enter_password': 'Enter password',
    'password_recovery': 'Password Recovery',
    'password_recovery_message': 'To recover your password, please contact your mentor. They will help you reset your password and restore access to your account.',
    'understood': 'Understood',
    'sign_in': 'Sign In',

    // Menu
    'menu': 'Menu',
    'profile': 'Profile',
    'profile_info': 'Profile Info',
    'settings': 'Settings',
    'language': 'Language',
    'change_language': 'Change language',
    'select_language': 'Select language',
    'change_password': 'Change password',
    'chats': 'Chats',
    'files': 'Files',
    'about': 'About app',

    // Jaidems
    'jaidems': 'Jaidemchiler',
    'search_jaidems': 'Search jaidemchiler...',
    'jaidems_not_found': 'Jaidemchiler not found',
    'change_search_criteria': 'Try changing search criteria',
    'advisors_not_found': 'Advisors not found',
    'advisors_not_found_description': 'No advisors available at the moment',

    // Filters
    'filter': 'Filter',
    'flow': 'Flow',
    'flow_number': 'Flow',
    'select_flow': 'Select flow',
    'generation': 'Generation',
    'select_generation': 'Select generation',
    'select_generation_first': 'Select generation first',
    'state': 'State',
    'select_state': 'Select state',
    'select_state_first': 'Select state first',
    'region': 'Region',
    'select_region': 'Select region',
    'select_district': 'Select district',
    'select_district_first': 'Select state first',
    'select_village': 'Select city/village',
    'select_village_first': 'Select district first',
    'no_districts_found': 'No districts found',
    'no_villages_found': 'No cities/villages found',
    'location': 'Place of birth',
    'university': 'University',
    'select_university': 'Select university',
    'search_university': 'Search university...',
    'universities_not_found': 'Universities not found',
    'speciality': 'Speciality',
    'select_speciality': 'Select speciality',
    'faculty': 'Faculty',
    'select_faculty': 'Select faculty',
    'select_faculty_first': 'Select faculty first',
    'age': 'Age',
    'years_old': 'years old',

    // Events
    'events': 'Events',
    'required_events': 'Required events',
    'optional_events': 'Optional',
    'event_details': 'Details',
    'event_date': 'Date and time',
    'event_location': 'Location',
    'event_generation': 'Generation',
    'event_description': 'Description',
    'event_conditions': 'Conditions',
    'event_contact': 'Contact',
    'event_video': 'Video',
    'event_passed': 'Event has passed',
    'event_not_happened': 'Event has not happened yet',
    'reviews_after_event': 'You can leave a review after the event',
    'required': 'Required',
    'loading_events': 'Loading events...',
    'events_load_error': 'Failed to load events',

    // Attendance
    'participants': 'Participants',
    'will_go': 'Will go',
    'will_not_go': 'Won\'t go',
    'maybe': 'Maybe',
    'i_want_to_participate': 'I want to participate',
    'your_answer': 'Your answer:',
    'change_answer': 'Change answer',
    'attendance_success': 'Request sent successfully!',
    'attendance_error': 'Failed to send, please try again later.',
    'decline_reason': 'Please specify the reason',
    'decline_reason_hint': 'Write your reason...',
    'send': 'Send',

    // Reviews
    'reviews': 'Reviews',
    'no_reviews': 'No reviews',
    'be_first_to_review': 'Be the first to leave a review!',
    'write_review': 'Write a review',
    'edit_review': 'Edit review',
    'new_review': 'New review',
    'your_review': 'You',
    'write_your_review': 'Write your review...',
    'delete_review': 'Delete review',
    'delete_review_confirm': 'Are you sure you want to delete your review?',
    'review_save_error': 'Failed to save review',
    'review_delete_error': 'Failed to delete review',

    // Likes
    'likes': 'Likes',

    // Goals
    'goals': 'Goals',
    'my_goals': 'My Goals',
    'manage_goals': 'Manage your goals',
    'add_goal': 'Add goal',
    'add_task': 'Add task',
    'add_indicator': 'Add indicator',
    'no_goals': 'No goals',
    'projects': 'Committees',
    'no_projects': 'No committees',
    'interested': 'interested',
    'i_am_interested': 'I\'m interested',
    'not_interested': 'Not interested',
    'start_adding_goal': 'Start adding your first goal!',
    'press_button_below': 'Press the button below',
    'progress': 'Progress',
    'deadline': 'Deadline',
    'remaining': 'Remaining',
    'days': 'days',
    'no_deadline': 'No deadline',
    'status_active': 'Active',
    'status_in_progress': 'In Progress',
    'status_completed': 'Completed',
    'status_paused': 'Paused',
    'status_changed': 'Changed',
    'status_cancelled': 'Cancelled',
    'edit_goal': 'Edit Goal',
    'new_goal': 'New Goal',
    'update_goal_info': 'Update your goal information',
    'set_goal_for_success': 'Set a goal to achieve success',
    'basic_info': 'Basic Information',
    'goal_name': 'Goal Name',
    'goal_name_hint': 'Learn English',
    'description_optional': 'Description (optional)',
    'description_hint': 'Briefly about your goal...',
    'deadline_and_frequency': 'Deadline and Frequency',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'currently': 'Currently',
    'select_date': 'Select date',
    'enter_manually': 'Enter manually',
    'enter_date_hint': 'DD-MM-YYYY',
    'invalid_date_format': 'Invalid format. Please enter in DD-MM-YYYY format',
    'frequency': 'Frequency',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'indicators': 'Indicators',
    'reminder': 'Reminder',
    'reminder_time': 'Reminder Time',
    'select_time': 'Select time',
    'goal_name_required': 'Goal name is required.',
    'name_min_length': 'Name must be at least 3 characters',
    'deadline_required': 'Target date is required',
    'deadline_past_error': 'Goal date cannot be in the past.',
    'frequency_required': 'Frequency is required',
    'reminder_time_required': 'Reminder time is required',
    'goal_updated_success': 'Goal updated successfully!',
    'goal_created_success': 'Goal created successfully!',
    'goal_and_indicators_created': 'Goal and indicators created successfully!',
    'indicator_create_error': 'Error creating indicator',
    'max_indicators': 'Maximum 3 indicators can be added',

    // Profile
    'edit_profile': 'Edit profile',
    'about_me': 'About me',
    'skills': 'Skills',
    'in_what_i_can_help': 'What I can help with',
    'what_i_need': 'What I need',
    'open_to': 'Open to',
    'vklad_to_jaidem': 'My contribution to Jaidem',
    'telegram': 'Telegram',
    'tags': 'Tags',
    'add_tag': 'Add tag',
    'member_category': 'Membership level',
    'interests': 'Interests',
    'course_year': 'Course',
    'village': 'City/village',
    'district': 'District',
    'information': 'Information',
    'unknown': 'Unknown',
    'call': 'Call',
    'write_message': 'Write',
    'contact': 'Contact',
    'booking_link': 'Booking Link',
    'phone': 'Phone',

    // Forum
    'forum': 'Forum',
    'feed': 'Feed',
    'posts': 'Posts',
    'profile_tab': 'Profile',
    'comments': 'Comments',
    'write_comment': 'Write a comment...',
    'no_posts': 'No posts',
    'no_posts_yet': 'No posts yet',
    'user_has_no_posts': 'This user has no posts',
    'error_loading_posts': 'Error loading posts',
    'share_profile': 'Share profile',
    'search_hint': 'Search...',

    // Video
    'video_load_error': 'Failed to load video',
    'open_in_youtube': 'Open in YouTube',

    // Languages
    'kyrgyz': 'Kyrgyz',
    'russian': 'Russian',
    'english': 'English',

    // Errors
    'error_occurred': 'An error occurred',
    'try_again': 'Try again',
    'no_internet': 'No internet connection',

    // Menu / Drawer
    'main_section': 'Main',
    'knowledge_base': 'Knowledge Base',
    'trainings': 'Rate Training',
    'chat_list': 'Chat List',
    'chat_with_admin': 'Chat with Admin',
    'chat_with_mentor': 'Chat with Mentor',
    'settings_section': 'Settings',
    'notifications': 'Notifications',
    'welcome': 'Welcome!',
    'select_menu_item': 'Select a section from the menu',
    'signing_out': 'Signing out...',
    'sign_out': 'Sign out',
    'sign_out_confirm': 'Do you want to sign out?',
    'sign_out_description': 'You will need to sign in again after signing out',
    'yes_sign_out': 'Yes, sign out',
    'sign_out_failed': 'Failed to sign out',

    // Bottom Navigation
    'nav_home': 'Home',
    'nav_jaidem': 'Jaidem',
    'nav_news': 'News',
    'nav_events': 'Events',
    'nav_profile': 'Profile',

    // Account Deletion
    'delete_account': 'Delete Account',
    'delete_account_title': 'Delete Account',
    'delete_account_description': 'When you delete your account, all your data will be permanently removed. This action cannot be undone.',
    'delete_account_confirm': 'Are you sure you want to delete your account?',
    'yes_delete': 'Yes, Delete',
    'account_deleted': 'Account successfully deleted',
    'delete_account_error': 'Failed to delete account',

    // Content Moderation
    'report': 'Report',
    'report_content': 'Report Content',
    'report_reason': 'Reason for Report',
    'report_spam': 'Spam',
    'report_inappropriate': 'Inappropriate Content',
    'report_harassment': 'Harassment or Bullying',
    'report_other': 'Other',
    'report_sent': 'Your report has been sent',
    'report_description': 'Additional information (optional)',
    'report_comment': 'Report Comment',
    'content_filtered_warning': 'Your message contains inappropriate language. Please modify the text.',
    'report_user': 'Report User',
    'block_user': 'Block User',
    'block_user_confirm': 'Do you want to block this user?',
    'user_blocked': 'User blocked',
    'unblock_user': 'Unblock',
    'user_unblocked': 'User unblocked',

    // Terms and Conditions
    'terms_title': 'Terms of Use',
    'terms_accept': 'I accept the terms of use',
    'terms_accept_button': 'Accept',
    'terms_must_accept': 'Please accept the terms to continue',
    'privacy_policy': 'Privacy Policy',
    'terms_content': 'By using the Jaidem app, you accept the following End User License Agreement (EULA):\\n\\nIMPORTANT: Jaidem maintains a ZERO TOLERANCE policy for objectionable content and abusive users.\\n\\n1. Respect: Treat other users with respect. Harassment, bullying, and discrimination are strictly prohibited.\\n2. Objectionable Content: Posting harmful, offensive, pornographic, or illegal content is prohibited. The app automatically filters content for inappropriate language.\\n3. Reporting and Blocking: Users can report objectionable content or abusive users using the "Report" button. You can also block any user to instantly remove their content from your feed.\\n4. Personal Data: Do not share other people\\\'s personal information without permission.\\n5. Spam: Do not post spam or advertisements.\\n\\nENFORCEMENT: Users who violate these rules will be immediately blocked and their content removed within 24 hours. All reports are reviewed by the developer and appropriate action is taken within 24 hours.\\n\\nBy continuing to use the app, you fully accept these terms.',

    // Training
    'training_rating': 'Rating',
    'training_questions': 'Questions',
    'training_flow_info': 'Flow Information',
    'training_name': 'Name',
    'training_description': 'Description',
    'training_year': 'Year',
    'training_attendance_stats': 'Attendance Statistics',
    'training_attendance': 'Attendance',
    'training_present': 'Present',
    'training_absent': 'Absent',
    'training_respectful': 'Excused',
    'training_total_participants': 'Total Participants',
    'training_participants_list': 'Participants List',
    'training_already_answered': 'You have already answered',
    'training_rating_accepted': 'Your training rating has been accepted',
    'training_rate_training': 'Rate the training',
    'training_opinion_important': 'Your opinion is important to us',
    'training_answer_questions': 'Answer questions',
    'training_answer_all_questions': 'Please answer all questions',
    'training_answers_sent': 'Answers sent successfully',
    'training_write_comment': 'Write your comment...',
    'training_submit': 'Submit',

    // Opros (Survey)
    'opros_before_survey': 'Before Survey',
    'opros_after_survey': 'After Survey',
    'opros_fill_survey': 'Take Survey',
    'opros_opens_on': 'Opens: ',
    'opros_submit': 'Submit',
    'opros_answer_required': 'Please answer the question',
    'opros_submitted_success': 'Survey submitted successfully!',
    'opros_write_answer': 'Write your answer...',
    'opros_survey': 'Survey',

    // Birthday reactions
    'birthday_congrats_button': 'Congratulate 🎉',
    'birthday_people_reacted': 'People congratulated you',
    'birthday_already_reacted': 'Congratulated ✓',
    'birthday_today': 'Birthday today!',
    'date_of_birth': 'Date of birth',
    'birthday_send_reaction': 'Congratulation sent!',

    // Posts
    'delete_post_title': 'Delete Post',
    'delete_post_confirm': 'Do you want to delete this post?',
    'post_deleted': 'Post deleted successfully',
    'post_updated': 'Post updated',
    'post_created': 'Post created',
    'no_posts_hint': 'Write your first post',
    'write_thoughts': 'Write your thoughts...',
    'new_post': 'New Post',
    'edit_post': 'Edit Post',
    'update_post_hint': 'Update your post',
    'share_thoughts': 'Share your thoughts',
    'photo': 'Photo',
    'add_photo': 'Add photo',
    'select_from_gallery': 'Select from gallery',
    'uploading': 'Uploading...',
    'content_label': 'Content',
    'content_required': 'Write some content',
    'saving': 'Saving...',
    'publish': 'Publish',
    'image_upload_error': 'Image upload error',

    // Change Password
    'set_new_password': 'Set a new password',
    'password_requirements': 'Password must be at least 8 characters and include letters and numbers.',
    'current_password': 'Current password',
    'enter_current_password': 'Enter current password',
    'new_password': 'New password',
    'enter_new_password': 'Enter new password',
    'password_min_length': 'Password must be at least 8 characters',
    'confirm_password': 'Confirm password',
    'repeat_new_password': 'Repeat new password',
    'passwords_dont_match': 'Passwords don\'t match',
    'password_changed': 'Password changed successfully!',

    // Forum
    'see_more': 'See more',
    'just_now': 'now',
    'minutes_short': 'min',
    'hours_short': 'h',
    'days_short': 'd',
    'weeks_short': 'w',
    'months_short': 'mo',
    'liked': 'Liked',
    'reply_action': 'Reply',
    'reply_to': 'reply to',
    'no_comments': 'No comments',
    'be_first_comment': 'Be the first to comment!',
    'write_reply': 'Write a reply...',
    'post_single': 'Post',
    'post_not_found': 'Post not found',
    'anonymous': 'Anonymous',

    // Training page
    'trainings_title': 'Trainings',
    'training_subtitle': 'Training courses',
    'no_trainings': 'No trainings',
    'no_trainings_available': 'No trainings available',
    'no_questions': 'No questions',

    // Profile Edit
    'education': 'Education',
    'interests_and_skills': 'Interests and Skills',
    'contact_info': 'Contact Information',
    'course_year_hint': 'Course year',
    'interests_hint': 'Interests (e.g: Football, Reading...)',
    'skills_hint': 'Skills (e.g: Programming, Design...)',
    'phone_hint': 'Phone number',
    'whatsapp_hint': 'WhatsApp number',
    'instagram_hint': 'Instagram username',
    'profile_saved': 'Profile saved successfully',
    'save_error': 'Save error',
    'image_uploaded': 'Image uploaded successfully',
    'tap_to_change_photo': 'Tap to change photo',
    'select_birthday': 'Select your birthday',
    'select_university_hint': 'Select university',
    'select_speciality_hint': 'Select speciality',
    'specialities_not_found': 'Specialities not found',
    'no_data': 'No data',
    'full_profile': 'View full profile',
    'no_university': 'Not studying at university',
    'other_education': 'Other Education',
    'work_experience': 'Work Experience',
    'add_school': 'Add school',
    'add_work_place': 'Add workplace',
    'success_history': 'Success History',
    'add_success': 'Add success',
    'success_name': 'Success name',
    'additional_education': 'Additional Education',
    'add_additional_education': 'Add education',
    'additional_education_title': 'Title',
    'school_name': 'School name',
    'work_place_name': 'Workplace name',
    'position': 'Position',
    'delete_confirm': 'Are you sure you want to delete?',
    'description': 'Description',

    // Jaidem popup
    'age_label': 'y.o.',
    'education_place': 'institution',
    'region_label': 'region',
    'additional_info': 'Additional information',
    'flow_label': 'Flow',
    'interests_label': 'Interests',
    'skills_label': 'Skills',
    'phone_label': 'Phone',
    'about_me_hint': 'Write about yourself...',
    'specialty': 'Speciality',
    'no_universities_found': 'No universities found',
    'year_suffix': ' year',

    // Person details
    'label_age': 'Age:',
    'label_course_year': 'Course year:',
    'label_specialty': 'Speciality:',
    'label_region': 'Region:',
    'label_village_city': 'Village/City:',
    'label_interests_skills': 'Interests/skills:',
    'label_phone': 'Phone:',
    'label_email': 'Email:',
    'specialty_profession': 'Speciality: ',
    'university_label': 'University: ',

    // Stories
    'stories_your_story': 'Your story',
    'stories_add': 'Add story',
    'stories_delete': 'Delete',
    'stories_delete_confirm': 'Delete this story?',
    'stories_deleted': 'Story deleted',
    'stories_upload_failed': 'Failed to upload photo',
    'stories_create_failed': 'Failed to create story',
    'stories_reply_hint': 'Send message...',
    'stories_reply_sent': 'Sent',
    'stories_reply_failed': 'Failed to send',
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['ky', 'ru', 'en'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => true;
}

// Extension for easy access
extension LocalizationExtension on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this)!;
  String tr(String key) => AppLocalizations.of(this)?.translate(key) ?? key;
}
